"""Regression and integration tests for the Tester role integration audit remediation."""

from pathlib import Path
from unittest.mock import patch
import yaml
from click.testing import CliRunner

from forge.cli import main, auto_pipeline
from forge.core.config import Config
from forge.core.role import Role
from forge.prompts.builder import Instruction
from forge.prompts.compiler import PromptCompiler
from forge.protocol.validator import MachineReportValidator
from forge.testing.browser import BrowserDriverFactory


# ==============================================================================
# 1. Config.default() contains Tester
# ==============================================================================

def test_config_default_contains_tester():
    """Verify Config.default() registers Tester as a first-class default stage."""
    cfg = Config.default()
    assert "tester" in cfg.stages, "Tester must be present in Config.default().stages"
    tester_cfg = cfg.stages["tester"]
    assert tester_cfg.adapter == "opencode"
    assert tester_cfg.effort == "high"

    # Serialized dict must include tester
    cfg_dict = cfg.to_dict()
    assert "tester" in cfg_dict["stages"]
    assert cfg_dict["stages"]["tester"]["adapter"] == "opencode"


# ==============================================================================
# 2. DEFAULT_FORGE_YAML generated by forge init includes Tester
# ==============================================================================

def test_forge_init_generates_tester_in_forge_yaml(tmp_path):
    """Verify forge init generates a forge.yaml containing the tester stage."""
    runner = CliRunner()
    with runner.isolated_filesystem(temp_dir=tmp_path):
        res = runner.invoke(main, ["init"])
        assert res.exit_code == 0
        cfg_file = Path("forge.yaml")
        assert cfg_file.exists()

        content = cfg_file.read_text(encoding="utf-8")
        parsed = yaml.safe_load(content)
        assert "stages" in parsed
        assert "tester" in parsed["stages"], "forge.yaml must include tester stage by default"
        assert parsed["stages"]["tester"].get("effort") == "high"


# ==============================================================================
# 3. forge doctor lists Tester and browser diagnostics
# ==============================================================================

def test_forge_doctor_lists_tester_and_browser_diagnostics(tmp_path):
    """Verify forge doctor lists Tester under configured stages and displays browser diagnostics."""
    runner = CliRunner()
    with runner.isolated_filesystem(temp_dir=tmp_path):
        res = runner.invoke(main, ["doctor"])
        assert res.exit_code == 0
        assert "• Tester" in res.output, "Tester must be listed in [Configured Stages]"
        assert "[Tester]" in res.output, "[Tester] diagnostic section must be present"
        assert "Browser Driver" in res.output
        assert "Evidence Collection" in res.output
        assert "✓ Enabled" in res.output
        assert "Browser Backend" in res.output


def test_forge_doctor_reports_browser_unavailable_guidance(tmp_path):
    """Verify forge doctor gives actionable installation guidance when browser automation is missing."""
    mock_diag = {
        "playwright_installed": False,
        "chromium_installed": False,
        "evidence_enabled": True,
        "backend_name": "MockBrowserDriver (fallback: browser automation unavailable)",
        "error_message": "Playwright package is not installed.",
    }
    runner = CliRunner()
    with runner.isolated_filesystem(temp_dir=tmp_path), \
         patch.object(BrowserDriverFactory, "check_environment", return_value=mock_diag):
        res = runner.invoke(main, ["doctor"])
        assert res.exit_code == 0
        assert "✗ Playwright missing" in res.output
        assert "✗ Chromium missing" in res.output
        assert "pip install playwright" in res.output
        assert "playwright install chromium" in res.output


# ==============================================================================
# 4. CLI messaging updates (help text, docstring, review resume_error)
# ==============================================================================

def test_cli_messaging_references_correct_pipeline(tmp_path):
    """Verify CLI help text, docstrings, and error messages reference the full pipeline including Tester."""
    runner = CliRunner()

    # forge auto --help
    res_help = runner.invoke(main, ["auto", "--help"])
    assert res_help.exit_code == 0
    norm_help = " ".join(res_help.output.split())
    assert "between Executor, Tester, and Reviewer" in norm_help
    assert "approved verification" in norm_help

    # auto_pipeline docstring
    assert "[Executor <-> (Tester -> Reviewer) Self-Repair Loop]" in (auto_pipeline.__doc__ or "")

    # forge review without prior run
    with runner.isolated_filesystem(temp_dir=tmp_path):
        res_rev = runner.invoke(main, ["review"])
        assert res_rev.exit_code == 1
        assert "Run 'forge architect', 'forge planner', 'forge execute', and 'forge test' first." in res_rev.output


# ==============================================================================
# 5. Prompt Transport Budget handles Tester and downstream Reviewer
# ==============================================================================

def test_prompt_budgeting_truncates_executor_report_for_tester():
    """Verify PromptCompiler.apply_transport_budget truncates executor_report when compiling Tester."""
    role = Role.load("tester")
    large_exec = "# Executor Claims\n" + ("Built feature endpoint.\n" * 1000)
    instruction = Instruction(
        role_name="tester",
        task="Test feature",
        executor_report=large_exec,
    )

    # Budget down to a small size
    budgeted = PromptCompiler.apply_transport_budget(
        instruction=instruction,
        role_template=role.template_content,
        max_prompt_bytes=5000,
    )
    assert budgeted.executor_report is not None
    assert "[... Executor report truncated" in budgeted.executor_report or "[... Executor report omitted" in budgeted.executor_report


def test_prompt_budgeting_truncates_tester_reports_for_reviewer():
    """Verify PromptCompiler.apply_transport_budget truncates tester reports when compiling Reviewer."""
    role = Role.load("reviewer")
    large_tester_md = "# Tester Report\n" + ("User flow verified.\n" * 1000)
    large_tester_json = '{"STATUS": "PASS", "DETAILS": "' + ("A" * 10000) + '"}'
    instruction = Instruction(
        role_name="reviewer",
        task="Review feature",
        tester_report=large_tester_md,
        tester_machine_report=large_tester_json,
    )

    budgeted = PromptCompiler.apply_transport_budget(
        instruction=instruction,
        role_template=role.template_content,
        max_prompt_bytes=6000,
    )
    assert budgeted.tester_report is not None
    assert "[... Tester markdown report truncated" in budgeted.tester_report or "[... Tester markdown report omitted" in budgeted.tester_report


# ==============================================================================
# 6. MachineReportValidator rejects TESTER reports containing SCORES
# ==============================================================================

def test_validator_rejects_tester_scores():
    """Verify MachineReportValidator rejects TESTER reports containing SCORES or SCORE."""
    data = {
        "ROLE": "TESTER",
        "STATUS": "PASS",
        "HANDOFF": "REVIEWER",
        "SCORES": {
            "FUNCTIONALITY": 9,
            "USABILITY": 8,
        },
    }
    report = MachineReportValidator.validate(data, expected_role="TESTER")
    assert report.is_valid is False
    assert any("strictly disallows 'SCORES'" in err for err in report.validation_errors)

    # Also test singular SCORE
    data_singular = {
        "ROLE": "TESTER",
        "STATUS": "PASS",
        "HANDOFF": "REVIEWER",
        "SCORE": 8.5,
    }
    report_singular = MachineReportValidator.validate(data_singular, expected_role="TESTER")
    assert report_singular.is_valid is False
    assert any("strictly disallows 'SCORES'" in err for err in report_singular.validation_errors)


def test_validator_accepts_clean_tester_report():
    """Verify MachineReportValidator accepts clean TESTER report without scores."""
    data = {
        "ROLE": "TESTER",
        "STATUS": "PASS",
        "HANDOFF": "REVIEWER",
        "ISSUES": {
            "CRITICAL": [],
            "MAJOR": [],
        },
    }
    report = MachineReportValidator.validate(data, expected_role="TESTER")
    assert report.is_valid is True
    assert report.status == "PASS"
    assert report.handoff == "REVIEWER"
